#!/bin/sh
## check_dj for check_dj in /Users/fresh/nagios/check_dj
##
## Made by Anthony Scalisi
## <scalisi.a@gmail.com>
##
## Started on  Mon May 21 10:53:24 2012 Anthony Scalisi
## Last update Mon May 21 10:53:39 2012 Anthony Scalisi
##

OK_STATE=0
WARNING_STATE=1
CRITICAL_STATE=2
UNKNOWN_STATE=3

count=0
count_workers=`ps -ef | grep delayed | grep -v grep | wc -l`
current=(`ps -ef | grep delayed | grep -v grep | awk '{print $11}' | sort -n`)
workers=( 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 )


#echo ${id[@]}  ## DEBUG

for e in ${current[@]}; do
        for n in ${workers[@]}; do
                if [ ${n} == ${e} ]; then
                        unset workers[$count]
                else
                        continue
                fi
                (( count++ ))
        done
done
#echo ${workers[@]} ## DEBUG


if [ $count_workers ==  16 ]
        then echo "OK - $count_workers DJ workers running"
        exit ${OK_STATE}
else
	if [[ $count_workers -gt 16 ]]
		then echo "WARNING - Too many workers ($count_workers) running."
		exit ${WARNING_STATE}
	elif [[ $count_workers -lt 16 ]]
		then echo "CRITICAL - only $count_workers workers are running ! Missing : ${workers[@]}"
		exit ${CRITICAL_STATE}
	fi
fi

