#!/usr/bin/env ruby

require 'yaml'

if ARGV.count != 0
  puts "Usage: #{$0}"
  exit UNKNOWN_STATE
end

OK_STATE = 0
WARNING_STATE = 1
CRITICAL_STATE = 2
UNKNOWN_STATE = 3

yml_path = '/home/deploy/www/taskrabbit/current/config'

dj = YAML.load_file("#{yml_path}/delayed_jobs.yml")['production']['servers'][`hostname`.strip]
wks = dj.collect { |wkr| wkr =~ /-i (\d{1,2})/; $1 }
min_prio = dj.collect { |min| min =~ /--min-priority (\d{1,})/; $1 }
max_prio = dj.collect { |max| max =~ /--max-priority (\d{1,})/; $1 }

#puts "Workers expected : #{wks.join(" ")}"
#puts "Minimum priority : #{min_prio.join(" ")}"
#puts "Maximum priority : #{max_prio.join(" ")}"

current_workers =`ps -ef | grep delayed | grep -v grep`.split("\n").map { |x| x.split("\s")[10] }
#puts "Workers : #{current_workers.join(" ")}"
#puts wks - current_workers
#workers = `ps -ef | grep delayed | grep -v grep`.collect { |job| job =~ / -i (\d{1,2})/; $1; }

if current_workers.count > wks.count
  puts "WARNING - There are too many DJ workers running : #{current_workers.count}"
  exit WARNING_STATE
elsif current_workers.count < wks.count
  puts "CRITICAL - Missing #{wks.count - current_workers.count} DJ workers ! Culprit : #{wks - current_workers}"
  exit CRITICAL_STATE
else
  puts "OK - #{current_workers.count} DJ workers currently running"
  exit OK_STATE
end